export const productList = [
  {
    id: 1,
    image: '/images/product1.png',
    title: 'classic monochromatic tees',
    slug: 'classic-monochromatic-tees',
    inStock: true,
    price: 35,
  },
  {
    id: 2,
    image: '/images/product2.png',
    title: 'monochromatic wardrobe',
    slug: 'monochromatic-wardrobe',
    inStock: true,
    price: 27,
  },
  {
    id: 3,
    image: '/images/product3.png',
    title: 'essential neutrals',
    slug: 'essential-neutrals',
    inStock: false,
    price: 22,
  },
  {
    id: 4,
    image: '/images/product4.png',
    title: 'utra net black',
    slug: 'utra-net-black',
    inStock: true,
    price: 43,
  },
  {
    id: 5,
    image: '/images/product1.png',
    title: 'classic monochromatic tees',
    slug: 'classic-monochromatic-tees-2',
    inStock: true,
    price: 35,
  },
  {
    id: 6,
    image: '/images/product2.png',
    title: 'monochromatic wardrobe',
    slug: 'monochromatic-wardrobe-2',
    inStock: true,
    price: 27,
  },
  {
    id: 7,
    image: '/images/product3.png',
    title: 'essential neutrals',
    slug: 'essential-neutrals-2',
    inStock: false,
    price: 22,
  },
  {
    id: 8,
    image: '/images/product4.png',
    title: 'utra net black',
    slug: 'utra-net-black-2',
    inStock: true,
    price: 43,
  },
];
